import {
  Badge,
  Lesson,
  Problem,
  Translation,
  AppLanguage,
  Theme,
  TestItem,
  LessonType,
} from "./types";

// Palette & Themes
export const COLORS = {
  primary: "#5A9CB5",
  secondary: "#FACE68",
  accent: "#FA6868",
  success: "#347433",
  darkText: "#1F2937",
  lightGreen: "#34D399",
};

// Expanded Theme Definition
export const THEMES: Record<
  Theme,
  {
    bg: string;
    card: string;
    text: string;
    sidebar: string;
    primary: string;
    secondary: string;
    accent: string;
  }
> = {
  light: {
    bg: "#F0F0D7",
    card: "#FFFFFF",
    text: "#1F2937",
    sidebar: "#FFFFFF",
    primary: "#5A9CB5",
    secondary: "#FACE68",
    accent: "#FA6868",
  },
  dark: {
    bg: "#1F2937",
    card: "#374151",
    text: "#F9FAFB",
    sidebar: "#111827",
    primary: "#60A5FA",
    secondary: "#FBBF24",
    accent: "#F87171",
  },
  midnight: {
    bg: "#0F172A",
    card: "#1E293B",
    text: "#E2E8F0",
    sidebar: "#020617",
    primary: "#38BDF8",
    secondary: "#818CF8",
    accent: "#C084FC",
  },
  candy: {
    bg: "#FFF5FA",
    card: "#FFFFFF",
    text: "#2B0A3D",
    sidebar: "#FFF0F5",
    primary: "#FF4D8D",
    secondary: "#FF8FB1",
    accent: "#FFD6E8",
  },
  orange: {
    bg: "#FFF6ED",
    card: "#FFFFFF",
    text: "#431407",
    sidebar: "#FFEDD5",
    primary: "#FF7A18",
    secondary: "#FFB347",
    accent: "#FFD8A8",
  },
  forest: {
    bg: "#EEF4EE",
    card: "#FFFFFF",
    text: "#1F2D24",
    sidebar: "#E6F0E6",
    primary: "#1F2D24",
    secondary: "#5F7F67",
    accent: "#9DB8A0",
  },
  coffee: {
    bg: "#FAF3E8",
    card: "#FFFFFF",
    text: "#5A3E2B",
    sidebar: "#F5EBE0",
    primary: "#5A3E2B",
    secondary: "#8B5E3C",
    accent: "#D6B48C",
  },
  golden: {
    bg: "#FFF9E6",
    card: "#FFFFFF",
    text: "#422006",
    sidebar: "#FEF3C7",
    primary: "#D4A017",
    secondary: "#FFCC33",
    accent: "#FFE8A3",
  },
  neon: {
    bg: "#F8FAFC",
    card: "#FFFFFF",
    text: "#0F172A",
    sidebar: "#F1F5F9",
    primary: "#0F172A",
    secondary: "#22D3EE",
    accent: "#A78BFA",
  },
  berry: {
    bg: "#FFF0F3",
    card: "#FFFFFF",
    text: "#2B0A3D",
    sidebar: "#FFE4E6",
    primary: "#2B0A3D",
    secondary: "#FF4D6D",
    accent: "#FFB3C1",
  },
  lemon: {
    bg: "#F8FAFC",
    card: "#FFFFFF",
    text: "#1E293B",
    sidebar: "#F1F5F9",
    primary: "#1E293B",
    secondary: "#FACC15",
    accent: "#FB7185",
  },
  cosmic: {
    bg: "#FDF4FF",
    card: "#FFFFFF",
    text: "#0B0F2A",
    sidebar: "#FAE8FF",
    primary: "#0B0F2A",
    secondary: "#EC4899",
    accent: "#8B5CF6",
  },
  aqua: {
    bg: "#ECFEFF",
    card: "#FFFFFF",
    text: "#022C22",
    sidebar: "#CCFBF1",
    primary: "#022C22",
    secondary: "#2DD4BF",
    accent: "#5EEAD4",
  },
};

export const BADGES: Badge[] = [
  {
    id: "first_steps",
    name: "First Steps",
    icon: "🚀",
    description: "Complete your first lesson",
    color: COLORS.secondary,
  },
  {
    id: "streak_3",
    name: "On Fire",
    icon: "🔥",
    description: "Reach a 3-day streak",
    color: COLORS.accent,
  },
  {
    id: "streak_7",
    name: "Week Warrior",
    icon: "⚡",
    description: "Reach a 7-day streak",
    color: COLORS.primary,
  },
  {
    id: "quiz_master",
    name: "Quiz Whiz",
    icon: "🧠",
    description: "Ace a quiz",
    color: COLORS.lightGreen,
  },
  {
    id: "master_coder",
    name: "Code Master",
    icon: "👑",
    description: "Complete 10 lessons",
    color: COLORS.primary,
  },
  {
    id: "bug_hunter",
    name: "Bug Hunter",
    icon: "🐛",
    description: "Fix an error",
    color: COLORS.success,
  },
  {
    id: "problem_solver",
    name: "Problem Solver",
    icon: "🧩",
    description: "Solve a practice problem",
    color: COLORS.secondary,
  },
];

export const PROBLEMS: Problem[] = [
  {
    id: "py_prob_1",
    title: "Sum of List",
    description: "Calculate the total of all numbers in a list.",
    language: "python",
    difficulty: "easy",
    instructions:
      "Create a list `nums = [10, 20, 30]` and print the sum of its elements.",
    initialCode: "nums = [10, 20, 30]\n# Print the sum",
    expectedOutput: "60",
    solutionCode: "nums = [10, 20, 30]\nprint(sum(nums))",
  },
  {
    id: "py_prob_2",
    title: "Check Even",
    description: "Check if a number is even.",
    language: "python",
    difficulty: "easy",
    instructions:
      "Set `x = 42`. If `x` is even, print 'Even'. Otherwise print 'Odd'.",
    initialCode: "x = 42\nif ... :\n    print('Even')",
    expectedOutput: "Even",
    solutionCode: "x = 42\nif x % 2 == 0:\n    print('Even')",
  },
  {
    id: "js_prob_1",
    title: "Reverse String",
    description: "Reverse the provided string.",
    language: "javascript",
    difficulty: "medium",
    instructions: "Given `let s = 'hello'`, reverse it and log the result.",
    initialCode: "let s = 'hello';\n// Reverse s and log it",
    expectedOutput: "olleh",
    solutionCode:
      "let s = 'hello';\nconsole.log(s.split('').reverse().join(''));",
  },
  {
    id: "js_prob_2",
    title: "Filter Positives",
    description: "Filter out negative numbers.",
    language: "javascript",
    difficulty: "medium",
    instructions:
      "Given `nums = [-1, 2, -3, 4]`, use filter to keep positive numbers and log the result.",
    initialCode: "const nums = [-1, 2, -3, 4];\n// Filter and log",
    expectedOutput: "2,4",
    solutionCode:
      "const nums = [-1, 2, -3, 4];\nconsole.log(nums.filter(n => n > 0));",
  },
];

export const BUG_HUNTER_LEVELS = [
  {
    id: 1,
    lang: "python",
    code: ["def greet()", '    print("Hello")'],
    errorLine: 0,
    hint: "Missing colon ':' at the end of function definition.",
  },
  {
    id: 2,
    lang: "javascript",
    code: ["const x = 10;", "x = 20;", "console.log(x);"],
    errorLine: 1,
    hint: "Cannot reassign a constant variable.",
  },
  {
    id: 3,
    lang: "python",
    code: ["if x = 10:", '    print("Equal")', "else:", '    print("Not")'],
    errorLine: 0,
    hint: "Use '==' for comparison, not '='.",
  },
  {
    id: 4,
    lang: "javascript",
    code: [
      'let colors = ["red", "blue"];',
      "console.log(colors[2]);",
      "// This prints undefined",
    ],
    errorLine: 1,
    hint: "Arrays are 0-indexed. Index 2 is out of bounds.",
  },
  {
    id: 5,
    lang: "python",
    code: ["my_list = [1, 2, 3]", "my_list.push(4)", "print(my_list)"],
    errorLine: 1,
    hint: "Python lists use .append(), not .push().",
  },
];

export const SCRAMBLE_LEVELS = [
  {
    id: 1,
    lang: "python",
    correctOrder: ["def greet():", "    print('Hello')"],
    display: ["    print('Hello')", "def greet():"],
  },
  {
    id: 2,
    lang: "javascript",
    correctOrder: ["let x = 10;", "if (x > 5) {", "  console.log('Big');", "}"],
    display: ["if (x > 5) {", "let x = 10;", "}", "  console.log('Big');"],
  },
  {
    id: 3,
    lang: "python",
    correctOrder: [
      "for i in range(5):",
      "    if i % 2 == 0:",
      "        print(i)",
    ],
    display: ["    if i % 2 == 0:", "        print(i)", "for i in range(5):"],
  },
  {
    id: 4,
    lang: "javascript",
    correctOrder: ["function add(a, b) {", "  return a + b;", "}"],
    display: ["  return a + b;", "}", "function add(a, b) {"],
  },
];

export const LEADERBOARD_DATA = [
  { id: 1, name: "CodeNinja", xp: 12500, badge: "👑" },
  { id: 2, name: "Pythoneer", xp: 9800, badge: "🔥" },
  { id: 3, name: "JSMaster", xp: 8750, badge: "⚡" },
  { id: 4, name: "AlgoWhiz", xp: 7200, badge: "🧠" },
  { id: 5, name: "BugSlayer", xp: 6540, badge: "🐛" },
];

export const CHEATSHEETS = {
  python: [
    { title: "Basics", content: "print('Hello')\n# Comment" },
    { title: "Variables", content: "x = 5\nname = 'Max'\nis_active = True" },
    {
      title: "Lists",
      content: "nums = [1, 2, 3]\nnums.append(4)\nprint(nums[0])",
    },
    {
      title: "Loops",
      content: "for i in range(5):\n  print(i)\n\nwhile x > 0:\n  x -= 1",
    },
    { title: "Functions", content: "def add(a, b):\n  return a + b" },
  ],
  javascript: [
    { title: "Basics", content: "console.log('Hello');\n// Comment" },
    {
      title: "Variables",
      content: "let x = 5;\nconst name = 'Max';\nlet isActive = true;",
    },
    {
      title: "Arrays",
      content: "let nums = [1, 2, 3];\nnums.push(4);\nconsole.log(nums[0]);",
    },
    {
      title: "Loops",
      content: "for(let i=0; i<5; i++){\n  console.log(i);\n}",
    },
    { title: "Functions", content: "function add(a, b){\n  return a + b;\n}" },
  ],
};

export const TRANSLATIONS: Record<AppLanguage, Translation> = {
  en: {
    welcome: "Welcome to MaXxCode",
    continue: "Continue",
    check: "Check Code",
    run: "Run Code",
    nextLesson: "Next Lesson",
    reset: "Reset Code",
    dashboard: "Learn",
    profile: "Profile",
    lessons: "Path",
    settings: "Settings",
    problems: "Problems",
    playground: "Playground",
    arcade: "Arcade",
    aboutDev: "About Dev",
    streak: "Day Streak",
    xp: "Total XP",
    developedBy: "Developed by Shaikh Aliakbar",
    loading: "Thinking...",
    successMsg: "Excellent! Code passed.",
    errorMsg: "Something is off. Check the output.",
    consoleOutput: "Console Output",
    selectLanguage: "Interface Language",
    selectTheme: "App Theme",
    completedTitle: "Lesson Complete!",
    comingSoon: "More Chapters Coming Soon!",
    locked: "Locked",
    start: "START",
    quizTitle: "Knowledge Check",
    submitQuiz: "Submit Answers",
    quizPassed: "Quiz Passed!",
    quizFailed: "Review the concepts and try again.",
    back: "Back",
    translateLesson: "Translate Explanation",
    lessonLanguage: "Lesson Language",
    solve: "Solve",
    difficulty: "Difficulty",
    unlockAll: "Unlock All Levels",
    unlockMsg:
      "It's better for you to learn level by level. However, if you have lost your progress or you know the previous topics and want to learn from the start, click here.",
    confirmUnlock: "Unlock Everything",
  },
  hi: {
    welcome: "MaXxCode में आपका स्वागत है",
    continue: "जारी रखें",
    check: "जाँच करें",
    run: "रन कोड",
    nextLesson: "अगला पाठ",
    reset: "रीसेट करें",
    dashboard: "सीखें",
    profile: "प्रोफाइल",
    lessons: "रास्ता",
    settings: "सेटिंग्स",
    problems: "समस्याएं",
    playground: "प्लेग्राउंड",
    arcade: "आर्केड",
    aboutDev: "डेवलपर के बारे में",
    streak: "स्ट्रिक",
    xp: "कुल XP",
    developedBy: "Shaikh Aliakbar द्वारा विकसित",
    loading: "सोच रहा हूँ...",
    successMsg: "बहुत बढ़िया! कोड सही है।",
    errorMsg: "कुछ गलत है। आउटपुट चेक करें।",
    consoleOutput: "कंसोल आउटपुट",
    selectLanguage: "भाषा चुनें",
    selectTheme: "थीम",
    completedTitle: "पाठ पूरा हुआ!",
    comingSoon: "जल्द ही आ रहा है!",
    locked: "बंद है",
    start: "शुरू करें",
    quizTitle: "प्रश्नोत्तरी",
    submitQuiz: "उत्तर जमा करें",
    quizPassed: "प्रश्नोत्तरी पास की!",
    quizFailed: "अवधारणाओं की समीक्षा करें और पुनः प्रयास करें।",
    back: "वापस",
    translateLesson: "अनुवाद करें",
    lessonLanguage: "पाठ की भाषा",
    solve: "हल करें",
    difficulty: "कठिनाई",
    unlockAll: "सभी स्तर अनलॉक करें",
    unlockMsg:
      "स्तर दर स्तर सीखना आपके लिए बेहतर है। हालाँकि, यदि आपने अपनी प्रगति खो दी है या आप पिछले विषयों को जानते हैं और शुरू से सीखना चाहते हैं, तो यहाँ क्लिक करें।",
    confirmUnlock: "सब कुछ अनलॉक करें",
  },
  hinglish: {
    welcome: "MaXxCode mein welcome hai!",
    continue: "Aage Badhein",
    check: "Check Karein",
    run: "Run Karein",
    nextLesson: "Next Lesson",
    reset: "Reset Karein",
    dashboard: "Learn",
    profile: "Profile",
    lessons: "Path",
    settings: "Settings",
    problems: "Problems",
    playground: "Playground",
    arcade: "Arcade",
    aboutDev: "About Dev",
    streak: "Streak",
    xp: "Total XP",
    developedBy: "Developed by Shaikh Aliakbar",
    loading: "Soch raha hoon...",
    successMsg: "Awesome! Code sahi hai.",
    errorMsg: "Kuch gadbad hai. Output dekhein.",
    consoleOutput: "Console Output",
    selectLanguage: "Language Chunein",
    selectTheme: "Theme",
    completedTitle: "Lesson Complete!",
    comingSoon: "Aur chapters aane wale hain!",
    locked: "Locked",
    start: "SHURU",
    quizTitle: "Quiz Time",
    submitQuiz: "Submit Karein",
    quizPassed: "Quiz Pass!",
    quizFailed: "Fir se try karein.",
    back: "Wapas",
    translateLesson: "Samjhao",
    lessonLanguage: "Lesson Language",
    solve: "Solve Karo",
    difficulty: "Mushkil Level",
    unlockAll: "Saare Levels Unlock Karein",
    unlockMsg:
      "Level by level seekhna behtar hai. Lekin agar aapne progress kho di hai ya aapko pehle se aata hai, toh yahan click karein.",
    confirmUnlock: "Sab Unlock Karein",
  },
};

// --------------------------------------------------------------------------
// CURRICULUM DEFINITION (STRICT 25 CHAPTERS)
// --------------------------------------------------------------------------

interface ChapterDef {
  title: string;
  py: {
    concept: string;
    task: string;
    init: string;
    sol: string;
    explain: string;
  };
  js: {
    concept: string;
    task: string;
    init: string;
    sol: string;
    explain: string;
  };
  questions: (lang: "python" | "javascript") => TestItem[];
}

const CHAPTERS: Record<number, ChapterDef> = {
  0: {
    title: "Intro: Welcome",
    py: {
      concept: "Python uses `print()` to show text.",
      task: "Print 'Hello, World!'",
      init: "print(...)",
      sol: "print('Hello, World!')",
      explain: "The standard first program.",
    },
    js: {
      concept: "JS uses `console.log()` to output text.",
      task: "Log 'Hello, World!'",
      init: "console.log(...)",
      sol: "console.log('Hello, World!')",
      explain: "Logs message to the console.",
    },
    questions: (lang) => [
      {
        id: "q1",
        type: "mcq",
        question: lang === "python" ? "Output function?" : "Output function?",
        options: ["print()", "log()", "console.log()", "out()"],
        correctIndex: lang === "python" ? 0 : 2,
      },
      {
        id: "q2",
        type: "mcq",
        question: "Text needs:",
        options: ["Quotes", "Brackets", "Hashtags"],
        correctIndex: 0,
      },
      {
        id: "q3",
        type: "code",
        question: "Print 'Hi'",
        solutionCode: lang === "python" ? "print('Hi')" : "console.log('Hi')",
      },
      {
        id: "q4",
        type: "code",
        question: "Print number 5",
        solutionCode: lang === "python" ? "print(5)" : "console.log(5)",
      },
      {
        id: "q5",
        type: "mcq",
        question: "Is this code?",
        options: ["Yes", "No"],
        correctIndex: 0,
      },
    ],
  },
  1: {
    title: "Chapter 1: First Steps",
    py: {
      concept: "Comments start with `#`. Indentation matters.",
      task: "Add a comment `# Test` and print `1`.",
      init: "print(1)",
      sol: "# Test\nprint(1)",
      explain: "Comment added.",
    },
    js: {
      concept: "Comments start with `//`. Sentences end with `;`.",
      task: "Add comment `// Test` and log `1`.",
      init: "console.log(1)",
      sol: "// Test\nconsole.log(1);",
      explain: "Syntax Correct.",
    },
    questions: (lang) => [
      {
        id: "q1",
        type: "mcq",
        question: "Comment symbol?",
        options: ["//", "#", "<!--", "%"],
        correctIndex: lang === "python" ? 1 : 0,
      },
      {
        id: "q2",
        type: "mcq",
        question: "Code grouping?",
        options: ["Indentation", "Braces", "Magic"],
        correctIndex: lang === "python" ? 0 : 1,
      },
      {
        id: "q3",
        type: "code",
        question: "Write a comment",
        solutionCode: lang === "python" ? "#" : "//",
      },
      {
        id: "q4",
        type: "code",
        question: "Print 'Start'",
        solutionCode:
          lang === "python" ? "print('Start')" : "console.log('Start')",
      },
      {
        id: "q5",
        type: "mcq",
        question: "Readable code is:",
        options: ["Bad", "Good"],
        correctIndex: 1,
      },
    ],
  },
  2: {
    title: "Chapter 2: Variables",
    py: {
      concept: "Store data: `name = 'Max'`.",
      task: "Create variable `score` = 10.",
      init: "score = ...",
      sol: "score = 10\nprint(score)",
      explain: "Variable assigned.",
    },
    js: {
      concept: "Use `let` or `const`. `let x = 10;`",
      task: "Declare `let score = 10;`",
      init: "let score ...",
      sol: "let score = 10;\nconsole.log(score);",
      explain: "Variable declared.",
    },
    questions: (lang) => [
      {
        id: "q1",
        type: "mcq",
        question: "Assignment operator?",
        options: ["==", "=", ":"],
        correctIndex: 1,
      },
      {
        id: "q2",
        type: "mcq",
        question: "Store text in?",
        options: ["String", "Int", "Bool"],
        correctIndex: 0,
      },
      {
        id: "q3",
        type: "code",
        question: "Set x to 5",
        solutionCode: lang === "python" ? "x = 5" : "let x = 5",
      },
      {
        id: "q4",
        type: "code",
        question: "Set y to 'Hi'",
        solutionCode: lang === "python" ? "y = 'Hi'" : "let y = 'Hi'",
      },
      {
        id: "q5",
        type: "mcq",
        question: "Can variables change?",
        options: ["Yes", "No"],
        correctIndex: 0,
      },
    ],
  },
  3: {
    title: "Chapter 3: Input",
    py: {
      concept: "Use `input()` to get user data.",
      task: "Ask for name and print it.",
      init: "name = input()",
      sol: "name = input()\nprint(name)",
      explain: "Input received.",
    },
    js: {
      concept: "In browsers, use `prompt()` (mocked here).",
      task: "Let name = prompt(); log it.",
      init: "let name = prompt()",
      sol: "let name = prompt();\nconsole.log(name);",
      explain: "Prompt used.",
    },
    questions: (lang) => [
      {
        id: "q1",
        type: "mcq",
        question: "Get user data?",
        options: ["input/prompt", "get()", "fetch()"],
        correctIndex: 0,
      },
      {
        id: "q2",
        type: "mcq",
        question: "Input returns?",
        options: ["String", "Int"],
        correctIndex: 0,
      },
      {
        id: "q3",
        type: "code",
        question: "Get input to x",
        solutionCode: lang === "python" ? "x = input()" : "let x = prompt()",
      },
      {
        id: "q4",
        type: "code",
        question: "Print input",
        solutionCode:
          lang === "python" ? "print(input())" : "console.log(prompt())",
      },
      {
        id: "q5",
        type: "mcq",
        question: "Is it interactive?",
        options: ["Yes", "No"],
        correctIndex: 0,
      },
    ],
  },
  4: {
    title: "Chapter 4: Conditions",
    py: {
      concept: "`if`, `elif`, `else` control flow.",
      task: "If x > 5 print 'Big'.",
      init: "x = 10\nif ...",
      sol: "x=10\nif x>5: print('Big')",
      explain: "Checked condition.",
    },
    js: {
      concept: "`if (cond) { ... } else { ... }`",
      task: "If (x > 5) log 'Big'.",
      init: "let x=10; if...",
      sol: "let x=10; if(x>5){console.log('Big')}",
      explain: "Block executed.",
    },
    questions: (lang) => [
      {
        id: "q1",
        type: "mcq",
        question: "Check equality?",
        options: ["=", "==", "==="],
        correctIndex: 1,
      },
      {
        id: "q2",
        type: "mcq",
        question: "Otherwise keyword?",
        options: ["else", "other", "not"],
        correctIndex: 0,
      },
      {
        id: "q3",
        type: "code",
        question: "Check if x is 1",
        solutionCode: lang === "python" ? "if x == 1:" : "if(x==1)",
      },
      {
        id: "q4",
        type: "code",
        question: "Else block",
        solutionCode: lang === "python" ? "else:" : "else",
      },
      {
        id: "q5",
        type: "mcq",
        question: "True AND False is?",
        options: ["True", "False"],
        correctIndex: 1,
      },
    ],
  },
  5: {
    title: "Chapter 5: Loops",
    py: {
      concept: "`for i in range(5):` repeats code.",
      task: "Print 0 to 2.",
      init: "for i in ...",
      sol: "for i in range(3):\n print(i)",
      explain: "Looped 3 times.",
    },
    js: {
      concept: "`for(let i=0; i<5; i++)` repeats.",
      task: "Log 0 to 2.",
      init: "for(let i=0...)",
      sol: "for(let i=0;i<3;i++){console.log(i)}",
      explain: "Standard loop.",
    },
    questions: (lang) => [
      {
        id: "q1",
        type: "mcq",
        question: "Repeat code?",
        options: ["Loop", "If", "Var"],
        correctIndex: 0,
      },
      {
        id: "q2",
        type: "mcq",
        question: "Stop loop?",
        options: ["break", "stop", "halt"],
        correctIndex: 0,
      },
      { id: "q3", type: "code", question: "Start a loop", solutionCode: "for" },
      {
        id: "q4",
        type: "code",
        question: "While x < 5",
        solutionCode: lang === "python" ? "while x < 5:" : "while(x<5)",
      },
      {
        id: "q5",
        type: "mcq",
        question: "Infinite loop is good?",
        options: ["No", "Yes"],
        correctIndex: 0,
      },
    ],
  },
  6: {
    title: "Chapter 6: Lists / Arrays",
    py: {
      concept: "Lists `[1,2]` hold items.",
      task: "Create list `l` with 1, 2.",
      init: "l = ...",
      sol: "l=[1,2]\nprint(l)",
      explain: "List created.",
    },
    js: {
      concept: "Arrays `[1,2]` hold items.",
      task: "Const `a` = [1, 2].",
      init: "const a = ...",
      sol: "const a=[1,2]; console.log(a);",
      explain: "Array created.",
    },
    questions: (lang) => [
      {
        id: "q1",
        type: "mcq",
        question: "Index starts at?",
        options: ["1", "0"],
        correctIndex: 1,
      },
      {
        id: "q2",
        type: "mcq",
        question: "Container type?",
        options: ["List/Array", "Int", "Char"],
        correctIndex: 0,
      },
      { id: "q3", type: "code", question: "Empty list", solutionCode: "[]" },
      {
        id: "q4",
        type: "code",
        question: "Access first item",
        solutionCode: "[0]",
      },
      {
        id: "q5",
        type: "mcq",
        question: "Can hold mixed types?",
        options: ["Yes", "No"],
        correctIndex: 0,
      },
    ],
  },
  7: {
    title: "Chapter 7: Dictionaries / Objects",
    py: {
      concept: "Key-Value pairs: `{'k':'v'}`.",
      task: "Create dict with key 'a':1.",
      init: "d = ...",
      sol: "d={'a':1}\nprint(d)",
      explain: "Dict created.",
    },
    js: {
      concept: "Objects `{k:v}` store properties.",
      task: "Obj `o` with key 'a':1.",
      init: "const o = ...",
      sol: "const o={a:1}; console.log(o);",
      explain: "Object created.",
    },
    questions: (lang) => [
      {
        id: "q1",
        type: "mcq",
        question: "Structure?",
        options: ["Key-Value", "Index-Value"],
        correctIndex: 0,
      },
      {
        id: "q2",
        type: "mcq",
        question: "Syntax?",
        options: ["{}", "[]", "()"],
        correctIndex: 0,
      },
      { id: "q3", type: "code", question: "Define empty", solutionCode: "{}" },
      {
        id: "q4",
        type: "code",
        question: "Access key 'k'",
        solutionCode: "['k']",
      },
      {
        id: "q5",
        type: "mcq",
        question: "Keys must be unique?",
        options: ["Yes", "No"],
        correctIndex: 0,
      },
    ],
  },
  8: {
    title: "Chapter 8: Functions",
    py: {
      concept: "`def name():` creates functions.",
      task: "Define `f` that prints 'Hi'.",
      init: "def f():",
      sol: "def f(): print('Hi')\nf()",
      explain: "Function defined.",
    },
    js: {
      concept: "`function name() {}` creates functions.",
      task: "Function `f` logs 'Hi'.",
      init: "function f()",
      sol: "function f(){console.log('Hi')}\nf();",
      explain: "Function defined.",
    },
    questions: (lang) => [
      {
        id: "q1",
        type: "mcq",
        question: "Keyword?",
        options: ["def/function", "func", "method"],
        correctIndex: 0,
      },
      {
        id: "q2",
        type: "mcq",
        question: "Send data back?",
        options: ["return", "back", "send"],
        correctIndex: 0,
      },
      {
        id: "q3",
        type: "code",
        question: "Call function f",
        solutionCode: "f()",
      },
      {
        id: "q4",
        type: "code",
        question: "Return 1",
        solutionCode: "return 1",
      },
      {
        id: "q5",
        type: "mcq",
        question: "Reusable?",
        options: ["Yes", "No"],
        correctIndex: 0,
      },
    ],
  },
  9: {
    title: "Chapter 9: Tuples / Structures",
    py: {
      concept: "Tuples `(1,2)` are immutable lists.",
      task: "Create tuple `t` = (1, 2).",
      init: "t = ...",
      sol: "t=(1,2)\nprint(t)",
      explain: "Tuple created.",
    },
    js: {
      concept: "JS uses `const` Arrays for fixed refs.",
      task: "Const array `c` = [1, 2].",
      init: "const c = ...",
      sol: "const c=[1,2];",
      explain: "Const array.",
    },
    questions: (lang) => [
      {
        id: "q1",
        type: "mcq",
        question: "Immutable means?",
        options: ["Unchangeable", "Fast"],
        correctIndex: 0,
      },
      {
        id: "q2",
        type: "mcq",
        question: "Python Syntax?",
        options: ["()", "[]"],
        correctIndex: 0,
      },
      {
        id: "q3",
        type: "code",
        question: "Create tuple/const",
        solutionCode: lang === "python" ? "(1,)" : "const",
      },
      {
        id: "q4",
        type: "code",
        question: "Access index 0",
        solutionCode: "[0]",
      },
      {
        id: "q5",
        type: "mcq",
        question: "Can add items?",
        options: ["No (Tuple)", "Yes (Array)"],
        correctIndex: lang === "python" ? 0 : 1,
      },
    ],
  },
  10: {
    title: "Chapter 10: Sets",
    py: {
      concept: "Sets `{1,2}` store unique items.",
      task: "Create set with 1, 1, 2.",
      init: "s = {1, 1, 2}",
      sol: "s={1,1,2}\nprint(s)",
      explain: "Duplicates removed.",
    },
    js: {
      concept: "`new Set([1,2])` stores unique items.",
      task: "New Set from [1,1,2].",
      init: "const s = ...",
      sol: "const s=new Set([1,1,2]);console.log(s);",
      explain: "Set created.",
    },
    questions: (lang) => [
      {
        id: "q1",
        type: "mcq",
        question: "Feature?",
        options: ["Unique items", "Ordered"],
        correctIndex: 0,
      },
      {
        id: "q2",
        type: "mcq",
        question: "Duplicates?",
        options: ["Removed", "Kept"],
        correctIndex: 0,
      },
      {
        id: "q3",
        type: "code",
        question: "Create set",
        solutionCode: lang === "python" ? "{1}" : "new Set",
      },
      { id: "q4", type: "code", question: "Add item", solutionCode: "add" },
      {
        id: "q5",
        type: "mcq",
        question: "Fast lookup?",
        options: ["Yes", "No"],
        correctIndex: 0,
      },
    ],
  },
  11: {
    title: "Chapter 11: Modules / Imports",
    py: {
      concept: "`import math` loads code.",
      task: "Import math, print pi.",
      init: "import ...",
      sol: "import math\nprint(math.pi)",
      explain: "Math loaded.",
    },
    js: {
      concept: "`import` or `require` loads code.",
      task: "Simulate `Math.PI` usage.",
      init: "console.log(...)",
      sol: "console.log(Math.PI);",
      explain: "Math used.",
    },
    questions: (lang) => [
      {
        id: "q1",
        type: "mcq",
        question: "Keyword?",
        options: ["import", "include", "using"],
        correctIndex: 0,
      },
      {
        id: "q2",
        type: "mcq",
        question: "Why use?",
        options: ["Reuse code", "Make slow"],
        correctIndex: 0,
      },
      {
        id: "q3",
        type: "code",
        question: "Import math",
        solutionCode: lang === "python" ? "import math" : "Math",
      },
      { id: "q4", type: "code", question: "Use Pi", solutionCode: "pi" },
      {
        id: "q5",
        type: "mcq",
        question: "Built-in libs?",
        options: ["Many", "None"],
        correctIndex: 0,
      },
    ],
  },
  12: {
    title: "Chapter 12: Errors / Exceptions",
    py: {
      concept: "`try: ... except:` handles crashes.",
      task: "Try print(x) except print 'Err'.",
      init: "try:",
      sol: "try:\n print(x)\nexcept:\n print('Err')",
      explain: "Caught error.",
    },
    js: {
      concept: "`try { ... } catch (e) { ... }`",
      task: "Try log(x) catch log 'Err'.",
      init: "try {",
      sol: "try{console.log(x)}catch(e){console.log('Err')}",
      explain: "Caught error.",
    },
    questions: (lang) => [
      {
        id: "q1",
        type: "mcq",
        question: "Catch block?",
        options: ["except/catch", "stop", "handle"],
        correctIndex: 0,
      },
      {
        id: "q2",
        type: "mcq",
        question: "Prevents crash?",
        options: ["Yes", "No"],
        correctIndex: 0,
      },
      {
        id: "q3",
        type: "code",
        question: "Start safe block",
        solutionCode: "try",
      },
      {
        id: "q4",
        type: "code",
        question: "Catch error",
        solutionCode: lang === "python" ? "except" : "catch",
      },
      {
        id: "q5",
        type: "mcq",
        question: "Always run code?",
        options: ["finally", "end"],
        correctIndex: 0,
      },
    ],
  },
  13: {
    title: "Chapter 13: Classes",
    py: {
      concept: "OOP: `class Dog:` defines objects.",
      task: "Class Dog with pass.",
      init: "class Dog:",
      sol: "class Dog:\n pass",
      explain: "Class defined.",
    },
    js: {
      concept: "OOP: `class Dog {}` defines objects.",
      task: "Class Dog.",
      init: "class Dog",
      sol: "class Dog {}",
      explain: "Class defined.",
    },
    questions: (lang) => [
      {
        id: "q1",
        type: "mcq",
        question: "Blueprint for obj?",
        options: ["Class", "Func", "Var"],
        correctIndex: 0,
      },
      {
        id: "q2",
        type: "mcq",
        question: "Create instance?",
        options: ["new / ()", "make", "build"],
        correctIndex: 0,
      },
      {
        id: "q3",
        type: "code",
        question: "Define class",
        solutionCode: "class",
      },
      {
        id: "q4",
        type: "code",
        question: "Self/This reference",
        solutionCode: lang === "python" ? "self" : "this",
      },
      {
        id: "q5",
        type: "mcq",
        question: "Has methods?",
        options: ["Yes", "No"],
        correctIndex: 0,
      },
    ],
  },
  14: {
    title: "Chapter 14: Inheritance",
    py: {
      concept: "Child classes inherit parent features.",
      task: "Class P, Class C(P).",
      init: "class P:\n pass",
      sol: "class P: pass\nclass C(P): pass",
      explain: "Inheritance.",
    },
    js: {
      concept: "`class C extends P`.",
      task: "Class C extends P.",
      init: "class C ...",
      sol: "class P{}\nclass C extends P{}",
      explain: "Inheritance.",
    },
    questions: (lang) => [
      {
        id: "q1",
        type: "mcq",
        question: "Get parent features?",
        options: ["Inheritance", "Copy", "Loop"],
        correctIndex: 0,
      },
      {
        id: "q2",
        type: "mcq",
        question: "Parent class ref?",
        options: ["super", "parent", "base"],
        correctIndex: 0,
      },
      {
        id: "q3",
        type: "code",
        question: "Extend keyword",
        solutionCode: lang === "python" ? "(" : "extends",
      },
      {
        id: "q4",
        type: "code",
        question: "Call parent init",
        solutionCode: lang === "python" ? "super().__init__" : "super()",
      },
      {
        id: "q5",
        type: "mcq",
        question: "Reuse code?",
        options: ["Yes", "No"],
        correctIndex: 0,
      },
    ],
  },
  15: {
    title: "Chapter 15: Iterators / Generators",
    py: {
      concept: "`yield` creates generators.",
      task: "Func yields 1.",
      init: "def g():",
      sol: "def g(): yield 1\nprint(next(g()))",
      explain: "Yield used.",
    },
    js: {
      concept: "`function*` and `yield`.",
      task: "Gen func yields 1.",
      init: "function* g()",
      sol: "function* g(){yield 1;}",
      explain: "Yield used.",
    },
    questions: (lang) => [
      {
        id: "q1",
        type: "mcq",
        question: "Pause function?",
        options: ["yield", "pause", "stop"],
        correctIndex: 0,
      },
      {
        id: "q2",
        type: "mcq",
        question: "Memory efficient?",
        options: ["Yes", "No"],
        correctIndex: 0,
      },
      {
        id: "q3",
        type: "code",
        question: "Yield value 5",
        solutionCode: "yield 5",
      },
      {
        id: "q4",
        type: "code",
        question: "Get next item",
        solutionCode: "next",
      },
      {
        id: "q5",
        type: "mcq",
        question: "Lazy evaluation?",
        options: ["Yes", "No"],
        correctIndex: 0,
      },
    ],
  },
  16: {
    title: "Chapter 16: Math Operations",
    py: {
      concept: "Use `pow`, `abs`, `round`.",
      task: "Print abs(-5).",
      init: "print(...)",
      sol: "print(abs(-5))",
      explain: "Absolute value.",
    },
    js: {
      concept: "Use `Math.abs`, `Math.pow`.",
      task: "Log Math.abs(-5).",
      init: "console.log(...)",
      sol: "console.log(Math.abs(-5))",
      explain: "Absolute value.",
    },
    questions: (lang) => [
      {
        id: "q1",
        type: "mcq",
        question: "Library?",
        options: ["math/Math", "calc", "num"],
        correctIndex: 0,
      },
      {
        id: "q2",
        type: "mcq",
        question: "Power function?",
        options: ["pow", "exp", "^"],
        correctIndex: 0,
      },
      {
        id: "q3",
        type: "code",
        question: "Absolute of -10",
        solutionCode: "abs(-10)",
      },
      { id: "q4", type: "code", question: "Square root", solutionCode: "sqrt" },
      {
        id: "q5",
        type: "mcq",
        question: "Round 3.6 -> 4?",
        options: ["round", "floor"],
        correctIndex: 0,
      },
    ],
  },
  17: {
    title: "Chapter 17: JSON / Data Handling",
    py: {
      concept: "`json` lib parses text.",
      task: "Import json, dumps dict.",
      init: "import json",
      sol: "import json\nprint(json.dumps({'a':1}))",
      explain: "JSON dumped.",
    },
    js: {
      concept: "`JSON.stringify` converts obj.",
      task: "Stringify {a:1}.",
      init: "JSON...",
      sol: "console.log(JSON.stringify({a:1}))",
      explain: "Stringified.",
    },
    questions: (lang) => [
      {
        id: "q1",
        type: "mcq",
        question: "Format name?",
        options: ["JSON", "XML", "CSV"],
        correctIndex: 0,
      },
      {
        id: "q2",
        type: "mcq",
        question: "Obj to Text?",
        options: ["dump/stringify", "parse", "read"],
        correctIndex: 0,
      },
      {
        id: "q3",
        type: "code",
        question: "Text to Obj",
        solutionCode: lang === "python" ? "loads" : "parse",
      },
      {
        id: "q4",
        type: "code",
        question: "Obj to Text",
        solutionCode: lang === "python" ? "dumps" : "stringify",
      },
      {
        id: "q5",
        type: "mcq",
        question: "Web standard?",
        options: ["Yes", "No"],
        correctIndex: 0,
      },
    ],
  },
  18: {
    title: "Chapter 18: Regular Expressions",
    py: {
      concept: "`re` module finds patterns.",
      task: "Find 'a' in 'cat'.",
      init: "import re",
      sol: "import re\nprint(re.search('a', 'cat'))",
      explain: "Pattern found.",
    },
    js: {
      concept: "`/pattern/` or RegExp.",
      task: "Test /a/ on 'cat'.",
      init: "/.../",
      sol: "console.log(/a/.test('cat'))",
      explain: "Pattern matched.",
    },
    questions: (lang) => [
      {
        id: "q1",
        type: "mcq",
        question: "Short name?",
        options: ["Regex", "Reg", "Pattern"],
        correctIndex: 0,
      },
      {
        id: "q2",
        type: "mcq",
        question: "Find digits?",
        options: ["\\d", "\\w", "\\s"],
        correctIndex: 0,
      },
      {
        id: "q3",
        type: "code",
        question: "Start pattern",
        solutionCode: lang === "python" ? "re." : "/",
      },
      {
        id: "q4",
        type: "code",
        question: "Search/Test",
        solutionCode: lang === "python" ? "search" : "test",
      },
      {
        id: "q5",
        type: "mcq",
        question: "Powerful?",
        options: ["Very", "No"],
        correctIndex: 0,
      },
    ],
  },
  19: {
    title: "Chapter 19: Files",
    py: {
      concept: "`open('f.txt')` reads files.",
      task: "Mock open 'file'.",
      init: "with open...",
      sol: "# mock\nprint('File read')",
      explain: "Simulated read.",
    },
    js: {
      concept: "Browser uses `File API` or fetch.",
      task: "Simulate fetch.",
      init: "fetch...",
      sol: "console.log('File fetched')",
      explain: "Simulated fetch.",
    },
    questions: (lang) => [
      {
        id: "q1",
        type: "mcq",
        question: "Open mode 'r'?",
        options: ["Read", "Write"],
        correctIndex: 0,
      },
      {
        id: "q2",
        type: "mcq",
        question: "Close file?",
        options: ["Important", "Optional"],
        correctIndex: 0,
      },
      {
        id: "q3",
        type: "code",
        question: "Open function",
        solutionCode: lang === "python" ? "open" : "fetch",
      },
      { id: "q4", type: "code", question: "Write mode", solutionCode: "w" },
      {
        id: "q5",
        type: "mcq",
        question: "Context Manager?",
        options: ["with", "using"],
        correctIndex: 0,
      },
    ],
  },
  20: {
    title: "Chapter 20: Flow Control",
    py: {
      concept: "`break` and `continue` loop control.",
      task: "Loop 5, break at 3.",
      init: "for i in range(5):",
      sol: "for i in range(5):\n if i==3: break",
      explain: "Broke loop.",
    },
    js: {
      concept: "`break` and `continue`.",
      task: "Loop 5, break at 3.",
      init: "for(;;)",
      sol: "for(let i=0;i<5;i++){if(i==3)break;}",
      explain: "Broke loop.",
    },
    questions: (lang) => [
      {
        id: "q1",
        type: "mcq",
        question: "Exit loop?",
        options: ["break", "exit", "quit"],
        correctIndex: 0,
      },
      {
        id: "q2",
        type: "mcq",
        question: "Skip iteration?",
        options: ["continue", "skip", "next"],
        correctIndex: 0,
      },
      {
        id: "q3",
        type: "code",
        question: "Stop loop keyword",
        solutionCode: "break",
      },
      {
        id: "q4",
        type: "code",
        question: "Skip keyword",
        solutionCode: "continue",
      },
      {
        id: "q5",
        type: "mcq",
        question: "Can nest?",
        options: ["Yes", "No"],
        correctIndex: 0,
      },
    ],
  },
  21: {
    title: "Chapter 21: Comprehensions / Maps",
    py: {
      concept: "`[x*2 for x in list]`.",
      task: "Double nums 1,2.",
      init: "nums=[1,2]",
      sol: "print([x*2 for x in [1,2]])",
      explain: "Comprehension.",
    },
    js: {
      concept: "`.map(x => x*2)` transforms.",
      task: "Map [1,2] to doubles.",
      init: "[1,2].map",
      sol: "console.log([1,2].map(x=>x*2))",
      explain: "Mapped.",
    },
    questions: (lang) => [
      {
        id: "q1",
        type: "mcq",
        question: "Short loop?",
        options: ["Comprehension/Map", "Shorty", "Quick"],
        correctIndex: 0,
      },
      {
        id: "q2",
        type: "mcq",
        question: "Returns new list?",
        options: ["Yes", "No"],
        correctIndex: 0,
      },
      { id: "q3", type: "code", question: "Square x", solutionCode: "x*x" },
      {
        id: "q4",
        type: "code",
        question: "Start symbol",
        solutionCode: lang === "python" ? "[" : ".map",
      },
      {
        id: "q5",
        type: "mcq",
        question: "Readable?",
        options: ["Yes", "No"],
        correctIndex: 0,
      },
    ],
  },
  22: {
    title: "Chapter 22: Lambda / Arrows",
    py: {
      concept: "`lambda x: x+1` is anonymous.",
      task: "Lambda adds 1 to x.",
      init: "f = lambda...",
      sol: "f=lambda x:x+1\nprint(f(1))",
      explain: "Lambda defined.",
    },
    js: {
      concept: "`x => x+1` is arrow func.",
      task: "Arrow func adds 1.",
      init: "const f = ...",
      sol: "const f=x=>x+1; console.log(f(1))",
      explain: "Arrow defined.",
    },
    questions: (lang) => [
      {
        id: "q1",
        type: "mcq",
        question: "Nameless func?",
        options: ["Lambda/Arrow", "Ghost", "Void"],
        correctIndex: 0,
      },
      {
        id: "q2",
        type: "mcq",
        question: "Syntax?",
        options: ["Short", "Long"],
        correctIndex: 0,
      },
      {
        id: "q3",
        type: "code",
        question: "Define keyword",
        solutionCode: lang === "python" ? "lambda" : "=>",
      },
      { id: "q4", type: "code", question: "Add a b", solutionCode: "a+b" },
      {
        id: "q5",
        type: "mcq",
        question: "Common in?",
        options: ["Functional", "OOP"],
        correctIndex: 0,
      },
    ],
  },
  23: {
    title: "Chapter 23: String Methods",
    py: {
      concept: "`.upper()`, `.strip()`, `.replace()`.",
      task: "Uppercase 'hi'.",
      init: "'hi'...",
      sol: "print('hi'.upper())",
      explain: "Uppercased.",
    },
    js: {
      concept: "`.toUpperCase()`, `.trim()`.",
      task: "Uppercase 'hi'.",
      init: "'hi'...",
      sol: "console.log('hi'.toUpperCase())",
      explain: "Uppercased.",
    },
    questions: (lang) => [
      {
        id: "q1",
        type: "mcq",
        question: "Make BIG?",
        options: ["upper", "big", "cap"],
        correctIndex: 0,
      },
      {
        id: "q2",
        type: "mcq",
        question: "Remove spaces?",
        options: ["strip/trim", "cut", "clean"],
        correctIndex: 0,
      },
      {
        id: "q3",
        type: "code",
        question: "Replace 'a' with 'b'",
        solutionCode: "replace",
      },
      {
        id: "q4",
        type: "code",
        question: "Split string",
        solutionCode: "split",
      },
      {
        id: "q5",
        type: "mcq",
        question: "Strings mutable?",
        options: ["No (Py) / No (JS)", "Yes"],
        correctIndex: 0,
      },
    ],
  },
  24: {
    title: "Chapter 24: Projects",
    py: {
      concept: "Combine skills: Calculator.",
      task: "Func add(a,b) prints sum.",
      init: "def add...",
      sol: "def add(a,b): print(a+b)\nadd(1,2)",
      explain: "Mini project.",
    },
    js: {
      concept: "Combine skills: Calculator.",
      task: "Func add(a,b) logs sum.",
      init: "function add...",
      sol: "function add(a,b){console.log(a+b)}\nadd(1,2)",
      explain: "Mini project.",
    },
    questions: (lang) => [
      {
        id: "q1",
        type: "mcq",
        question: "Goal?",
        options: ["Apply skills", "Waste time"],
        correctIndex: 0,
      },
      {
        id: "q2",
        type: "mcq",
        question: "Structure?",
        options: ["Functions", "Spaghetti"],
        correctIndex: 0,
      },
      { id: "q3", type: "code", question: "Call func", solutionCode: "(" },
      {
        id: "q4",
        type: "code",
        question: "Print result",
        solutionCode: "print",
      },
      {
        id: "q5",
        type: "mcq",
        question: "Fun?",
        options: ["Yes", "Yes"],
        correctIndex: 0,
      },
    ],
  },
  25: {
    title: "Chapter 25: Revision",
    py: {
      concept: "Review: Vars, Loops, Logic.",
      task: "Loop 3 times, print 'Rev'.",
      init: "for...",
      sol: "for i in range(3): print('Rev')",
      explain: "Revised.",
    },
    js: {
      concept: "Review: Vars, Loops, Logic.",
      task: "Loop 3 times, log 'Rev'.",
      init: "for...",
      sol: "for(let i=0;i<3;i++) console.log('Rev')",
      explain: "Revised.",
    },
    questions: (lang) => [
      {
        id: "q1",
        type: "mcq",
        question: "Ready for more?",
        options: ["Yes!", "No"],
        correctIndex: 0,
      },
      {
        id: "q2",
        type: "mcq",
        question: "Best way to learn?",
        options: ["Practice", "Reading"],
        correctIndex: 0,
      },
      {
        id: "q3",
        type: "code",
        question: "Final print",
        solutionCode: "print",
      },
      { id: "q4", type: "code", question: "Done?", solutionCode: "True" },
      {
        id: "q5",
        type: "mcq",
        question: "Mastered basics?",
        options: ["Yes", "Not yet"],
        correctIndex: 0,
      },
    ],
  },
};

// --------------------------------------------------------------------------
// GENERATE LESSONS
// --------------------------------------------------------------------------

export const LESSONS: Lesson[] = [];

const generateLessons = () => {
  Object.entries(CHAPTERS).forEach(([key, chap]) => {
    const order = parseInt(key);

    // --- PYTHON ---
    LESSONS.push({
      id: `py_${order}_1`,
      type: "code",
      title: chap.title,
      description: chap.py.concept,
      language: "python",
      order: order,
      chapter: chap.title,
      content: {
        intro: chap.py.concept,
        summary: [chap.py.concept, "Keep practicing.", "You got this!"],
        instructions: chap.py.task,
        initialCode: chap.py.init,
        solutionCode: chap.py.sol,
        expectedOutput: "...",
        codeExplanation: chap.py.explain,
      },
    });
    LESSONS.push({
      id: `py_${order}_test`,
      type: "test",
      title: `${chap.title} Test`,
      description: "Prove your skills.",
      language: "python",
      order: order + 0.5,
      chapter: chap.title,
      content: {
        passThreshold: 0.6,
        testItems: chap.questions("python"),
      },
    });

    // --- JAVASCRIPT ---
    LESSONS.push({
      id: `js_${order}_1`,
      type: "code",
      title: chap.title,
      description: chap.js.concept,
      language: "javascript",
      order: order,
      chapter: chap.title,
      content: {
        intro: chap.js.concept,
        summary: [chap.js.concept, "Keep practicing.", "You got this!"],
        instructions: chap.js.task,
        initialCode: chap.js.init,
        solutionCode: chap.js.sol,
        expectedOutput: "...",
        codeExplanation: chap.js.explain,
      },
    });
    LESSONS.push({
      id: `js_${order}_test`,
      type: "test",
      title: `${chap.title} Test`,
      description: "Prove your skills.",
      language: "javascript",
      order: order + 0.5,
      chapter: chap.title,
      content: {
        passThreshold: 0.6,
        testItems: chap.questions("javascript"),
      },
    });
  });
};

generateLessons();

console.log(
  `Generated ${LESSONS.length} lessons covering Intro + 25 Chapters for Py/JS.`
);
